import { ArrowLeft } from "lucide-react";
import { type CartItem, type Customer, type DeliveryAddress, type PaymentMethod, cartItemTotal, cartSubtotal, money } from "./types";

type Props = { items: CartItem[]; fulfillment: "delivery" | "retirada"; address: DeliveryAddress; customer: Customer; payment: PaymentMethod; deliveryFee: number; busy: boolean; error: string; onBack: () => void; onConfirm: () => void };
export default function ReviewPage({ items, fulfillment, address, customer, payment, deliveryFee, busy, error, onBack, onConfirm }: Props) {
  const subtotal = cartSubtotal(items);
  const fee = fulfillment === "delivery" ? deliveryFee : 0;
  return <main className="min-h-screen bg-[#fbf5d9] px-4 py-6 text-[#295727] sm:px-8"><div className="mx-auto max-w-2xl"><button onClick={onBack} className="mb-5 inline-flex items-center gap-2 text-sm text-[#54715b]"><ArrowLeft size={17}/> Voltar</button><p className="text-[11px] font-bold uppercase tracking-widest text-[#b52327]">Revisão final</p><h1 className="mt-1 font-serif text-3xl font-bold text-[#155b3b]">Resumo do pedido</h1>
    <section className="mt-5 rounded-xl border border-[#e5ddbd] bg-[#fffbea] p-5"><h2 className="font-serif text-lg font-bold">Itens</h2><div className="mt-3 divide-y divide-[#eee8d4]">{items.map((item) => <div key={item.cartKey} className="flex justify-between gap-4 py-3 text-sm"><span>{item.quantity} × {item.name}{item.additions.map((addition) => <small key={addition.menuItemId} className="block text-[#54715b]">+ {addition.name}{addition.quantityPerItem > 1 ? ` × ${addition.quantityPerItem}` : ""}</small>)}{item.observation && <small className="block text-[#71826a]">Obs.: {item.observation}</small>}</span><strong className="whitespace-nowrap">{money(cartItemTotal(item))}</strong></div>)}</div>
      <h2 className="mt-5 font-serif text-lg font-bold">Entrega e contato</h2><p className="mt-2 text-sm">{fulfillment === "delivery" ? `${address.rua}, ${address.numero} — ${address.bairro}, ${address.cep}` : "Retirada no local"}</p><p className="mt-1 text-sm">{customer.name} · {customer.whatsapp}</p><p className="mt-1 text-sm">Pagamento: {payment === "pix" ? "Pix" : payment === "cartao" ? "Cartão" : "Dinheiro"}</p>
      <div className="mt-5 space-y-2 border-t border-[#e9e2c9] pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(subtotal)}</span></div>{fulfillment === "delivery" && <div className="flex justify-between"><span>Taxa de entrega</span><span>{money(fee)}</span></div>}<div className="flex justify-between border-t border-[#e9e2c9] pt-3 text-base font-bold"><span>Total</span><span className="text-[#b52327]">{money(subtotal + fee)}</span></div></div>
    </section>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy || !items.length} onClick={onConfirm} className="mt-5 h-12 w-full rounded-lg bg-[#b51e24] font-semibold text-[#fff9df] disabled:opacity-50">{busy ? "Enviando pedido…" : "Confirmar pedido"}</button></div></main>;
}
