import { useEffect, useState } from "react";
import type { DragEvent } from "react";
import { ArrowLeft, RefreshCw, X } from "lucide-react";
import { publicSupabase } from "../../lib/supabase";
import { money, paymentLabels, statusLabels, type Order, type OrderStatus } from "./types";
import "./AdminPedidos.css";

const columns: OrderStatus[] = ["recebido", "em_preparo", "saiu_para_entrega", "entregue", "cancelado"];
const formatTime = (date: string) => new Date(date).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" });

export default function AdminPedidosKanbanInteractive() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null);
  const [draggingOrderId, setDraggingOrderId] = useState<string | null>(null);
  const [dropTarget, setDropTarget] = useState<OrderStatus | null>(null);
  const loadOrders = async () => { if (!publicSupabase) return; const { data } = await publicSupabase.from("pedidos").select("*, pedido_itens(*)").order("created_at", { ascending: true }); setOrders((data ?? []) as Order[]); setLoading(false); };
  useEffect(() => { void loadOrders(); const client = publicSupabase; if (!client) return; const channel = client.channel("kanban-pedidos-interactive").on("postgres_changes", { event: "*", schema: "public", table: "pedidos" }, () => void loadOrders()).subscribe(); return () => { void client.removeChannel(channel); }; }, []);
  const move = async (order: Order, status: OrderStatus) => { if (!publicSupabase || order.status === status) return; const previous = order.status; setOrders((current) => current.map((item) => item.id === order.id ? { ...item, status } : item)); setSelectedOrder((current) => current?.id === order.id ? { ...current, status } : current); const { error } = await publicSupabase.from("pedidos").update({ status }).eq("id", order.id); if (error) { setOrders((current) => current.map((item) => item.id === order.id ? { ...item, status: previous } : item)); setSelectedOrder((current) => current?.id === order.id ? { ...current, status: previous } : current); } };
  const startDragging = (event: DragEvent<HTMLElement>, order: Order) => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", order.id); setDraggingOrderId(order.id); };
  const finishDragging = () => { setDraggingOrderId(null); setDropTarget(null); };
  const allowDrop = (event: DragEvent<HTMLElement>, column: OrderStatus) => { event.preventDefault(); event.dataTransfer.dropEffect = "move"; setDropTarget(column); };
  const dropOrder = (event: DragEvent<HTMLElement>, column: OrderStatus) => { event.preventDefault(); const order = orders.find((item) => item.id === event.dataTransfer.getData("text/plain")); if (order) void move(order, column); finishDragging(); };
  return <main className="kanban-page"><header className="kanban-top"><div><a className="back-admin" href="/admin/pedidos"><ArrowLeft size={16} /> Pedidos</a><p className="orders-eyebrow">CENTRAL DE PRODUÇÃO</p><h1>Kanban de pedidos</h1><p className="kanban-hint">Clique em um card para ver todos os dados do pedido.</p></div><button className="refresh-button" onClick={() => void loadOrders()} title="Atualizar pedidos"><RefreshCw size={17} /> Atualizar</button></header><div className="kanban-board">{columns.map((column) => <section className={`kanban-column column-${column}${dropTarget === column ? " is-drop-target" : ""}`} key={column} onDragOver={(event) => allowDrop(event, column)} onDragEnter={(event) => allowDrop(event, column)} onDragLeave={(event) => { if (event.currentTarget === event.target) setDropTarget(null); }} onDrop={(event) => dropOrder(event, column)}><header><div><span className="column-dot" /><h2>{statusLabels[column]}</h2></div><b>{orders.filter((order) => order.status === column).length}</b></header><div className="kanban-cards">{loading ? <p className="kanban-empty">Carregando...</p> : orders.filter((order) => order.status === column).map((order) => <article className={`kanban-card${draggingOrderId === order.id ? " is-dragging" : ""}`} draggable onDragStart={(event) => startDragging(event, order)} onDragEnd={finishDragging} onClick={() => setSelectedOrder(order)} key={order.id}><div className="kanban-card-top"><strong>#{order.numero_pedido}</strong><time>{formatTime(order.created_at)}</time></div><h3>{order.nome_cliente}</h3><p>{order.pedido_itens.map((item) => `${item.quantidade}x ${item.nome_produto}`).join(" · ")}</p><div className="kanban-card-bottom"><span>{order.tipo_entrega === "delivery" ? "Delivery" : "Retirada"} · {paymentLabels[order.forma_pagamento]}</span><b>{money(order.total)}</b></div></article>)}</div></section>)}</div>{selectedOrder && <KanbanOrderDetails order={selectedOrder} onClose={() => setSelectedOrder(null)} onStatus={(status) => void move(selectedOrder, status)} />}</main>;
}

function KanbanOrderDetails({ order, onClose, onStatus }: { order: Order; onClose: () => void; onStatus: (status: OrderStatus) => void }) {
  return <div className="kanban-detail-backdrop" onMouseDown={onClose}><aside className="kanban-detail-panel" onMouseDown={(event) => event.stopPropagation()}><header><div><p className="orders-eyebrow">DETALHES DO PEDIDO</p><h2>#{order.numero_pedido}</h2><small>{order.nome_cliente} · {formatTime(order.created_at)}</small></div><button onClick={onClose} aria-label="Fechar detalhes"><X size={19} /></button></header><section><h3>Cliente</h3><p><strong>{order.nome_cliente}</strong><br />{order.telefone_cliente}</p></section><section><h3>{order.tipo_entrega === "delivery" ? "Entrega" : "Retirada"}</h3><p>{order.tipo_entrega === "delivery" ? `${order.rua}, ${order.numero}${order.complemento ? `, ${order.complemento}` : ""} - ${order.bairro}${order.cep ? ` · CEP ${order.cep}` : ""}` : "Retirada no local"}</p>{order.referencia && <small>Referência: {order.referencia}</small>}</section><section><h3>Itens do pedido</h3><div className="kanban-detail-items">{order.pedido_itens.map((item) => <div key={item.id}><span><strong>{item.quantidade}x</strong> {item.nome_produto}{item.observacao && <small>{item.observacao}</small>}</span><b>{money(item.subtotal)}</b></div>)}</div></section>{order.observacao && <section><h3>Observação</h3><p>{order.observacao}</p></section>}<section className="kanban-detail-finance"><div><span>Subtotal</span><b>{money(order.subtotal)}</b></div><div><span>Taxa de entrega</span><b>{money(order.taxa_entrega)}</b></div><div className="kanban-detail-total"><strong>Total</strong><b>{money(order.total)}</b></div><div><span>Pagamento</span><b>{paymentLabels[order.forma_pagamento]}</b></div></section><label className="kanban-detail-status">Status<select value={order.status} onChange={(event) => onStatus(event.target.value as OrderStatus)}>{columns.map((status) => <option value={status} key={status}>{statusLabels[status]}</option>)}</select></label></aside></div>;
}
